import Form from './components/form';
import Submit from './components/submit';
import TextField from './components/textField';
import Email from './components/textFields/email';
import Password from './components/textFields/password';
import Confirmation from './components/textFields/confirmation';
import FlagField from './components/textFields/flagFields';
import RadioGroup from './components/radio/group';
import RadioButton from './components/radio/button';
const application = require('./styles/application.scss');
const form = require('./styles/form.scss');
const input = require('./styles/inputs/textField.scss');
const radio = require('./styles/inputs/radio.scss');
const flagbox = require('./styles/inputs/flagbox.scss');
const flagInput = require('./styles/inputs/flagInput.scss');
const countries = require('./styles/inputs/countries.scss');
const submit = require('./styles/submit.scss');
const error = require('./styles/error.scss');
const underline = require('./styles/underline.scss');

export { Form, Submit, TextField, Email, FlagField, RadioGroup, RadioButton, Password, Confirmation };