import Form from './components/form';
import Submit from './components/submit';
import TextInput from './components/textInput';
import Email from './components/textInputs/email';
import Password from './components/textInputs/password';
import Confirmation from './components/textInputs/confirmation';
import FlagContainer from './components/flagContainer';
import Phone from './components/phone';
const application = require('./styles/application.scss');
const form = require('./styles/form.scss');
const input = require('./styles/inputs/textInput.scss');
const radio = require('./styles/inputs/radio.scss');
const flagbox = require('./styles/inputs/flagbox.scss');
const flagInput = require('./styles/inputs/flagInput.scss');
const countries = require('./styles/inputs/countries.scss');
const submit = require('./styles/submit.scss');
const error = require('./styles/error.scss');
const underline = require('./styles/underline.scss');

export { Form, Submit, TextInput, Email, FlagContainer, Phone, Password, Confirmation };